language: go

go:
  - 1.4

install:
  - go get -d -v ./... && go build -v ./...
  - go get -u golang.org/x/tools/cmd/vet;

script:
    # Put each test command on its own line.
  - go test -v ./...
  - go tool vet .

notifications:
  email:
    on_success: never
    on_failure: change
